// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://docqbofjrnkvulczfwav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvY3Fib2Zqcm5rdnVsY3pmd2F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMzkyMzYsImV4cCI6MjA2ODkxNTIzNn0.VQFx-K3Wbay60Qo2HKjt63Cw_bTVfhU5LU2okWk1A7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});